### ISSUE TITLE
Decide whether to use Python 2.7 or 3.0

### ISSUE THREAD

**Issue by alicoding** [mozilla/api.mozillascience.org#1]
We want to create an API server using Python, but don't have good reason as to which Python version to choose here.

**Comment by alicoding** [comment]
@pmclanahan Do you have any suggestion here?

**Comment by pmclanahan** [comment]
2.7 is still the safe bet, but depending on the libraries you'll need you're very likely to find Py3 compatible versions. I know some teams at Moz are using Python 3.4 or 3.5 with success, so if you can do it then for future-proofing I think it's a good idea. If you can't because some critical lib is py 2.7 only then you can do things that will help you transition to 3.5 later like:

```python
from __future__ import unicode_literals, print_function, absolute_imports
```

That gets your code close to Python 3 and possibly even able to run on both.

**Comment by alicoding** [comment]
cc @simonwex @gideonthomas @acabunoc

**Comment by gideonthomas** [comment]
After feedback from @ryanpitts, it looks like we're going to start with Python 3.4 since we don't think we're going to be super-reliant on libraries that are incompatible with it. If we do encounter such a problem we can find alternative libraries or shim the existing ones. Either way, we can cross that bridge when we come to it.
